import { Test, TestingModule } from '@nestjs/testing';
import { PostsService } from './posts.service';
import { getSuperHttpClientToken } from 'super-http/nestjs';

// ─── Mocks ────────────────────────────────────────────────────────────────────

const mockPostsClient = {
  get:     jest.fn(),
  request: jest.fn(),
};

const mockCommentsClient = {
  get: jest.fn(),
};

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('PostsService', () => {
  let service: PostsService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        PostsService,
        // Inject named clients using the DI tokens generated by getSuperHttpClientToken
        { provide: getSuperHttpClientToken('POSTS'),    useValue: mockPostsClient    },
        { provide: getSuperHttpClientToken('COMMENTS'), useValue: mockCommentsClient },
      ],
    }).compile();

    service = module.get<PostsService>(PostsService);
    jest.clearAllMocks();
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  // ── findAll ────────────────────────────────────────────────────────────────

  describe('findAll', () => {
    it('returns a list of posts', async () => {
      const posts = [
        { id: 1, userId: 1, title: 'Post 1', body: 'Body 1' },
        { id: 2, userId: 1, title: 'Post 2', body: 'Body 2' },
      ];
      mockPostsClient.get.mockResolvedValue({ data: posts });

      const result = await service.findAll();

      expect(result).toEqual(posts);
      expect(mockPostsClient.get).toHaveBeenCalledWith('/posts');
    });
  });

  // ── findOne ────────────────────────────────────────────────────────────────

  describe('findOne', () => {
    it('returns a single post by id', async () => {
      const post = { id: 1, userId: 1, title: 'Post 1', body: 'Body 1' };
      mockPostsClient.get.mockResolvedValue({ data: post });

      const result = await service.findOne(1);

      expect(result).toEqual(post);
      expect(mockPostsClient.get).toHaveBeenCalledWith('/posts/1');
    });
  });

  // ── findWithComments ───────────────────────────────────────────────────────

  describe('findWithComments', () => {
    it('returns a post merged with its comments', async () => {
      const post     = { id: 1, userId: 1, title: 'Post 1', body: 'Body 1' };
      const comments = [{ id: 1, postId: 1, name: 'Ana', email: 'a@b.com', body: 'Great!' }];

      mockPostsClient.get.mockResolvedValue({ data: post });
      mockCommentsClient.get.mockResolvedValue({ data: comments });

      const result = await service.findWithComments(1);

      expect(result).toEqual({ ...post, comments });
      expect(mockPostsClient.get).toHaveBeenCalledWith('/posts/1');
      expect(mockCommentsClient.get).toHaveBeenCalledWith('/posts/1/comments');
    });

    it('returns an empty comments array when comments client falls back', async () => {
      const post = { id: 2, userId: 1, title: 'Post 2', body: 'Body 2' };
      mockPostsClient.get.mockResolvedValue({ data: post });
      // Simulate fallback — commentsClient returns empty array after resilience kicks in
      mockCommentsClient.get.mockResolvedValue({ data: [] });

      const result = await service.findWithComments(2);

      expect(result.comments).toEqual([]);
    });
  });

  // ── create ─────────────────────────────────────────────────────────────────

  describe('create', () => {
    it('creates a post with retry disabled', async () => {
      const dto  = { userId: 1, title: 'New Post', body: 'Content' };
      const post = { id: 101, ...dto };
      mockPostsClient.request.mockResolvedValue({ data: post });

      const result = await service.create(dto);

      expect(result).toEqual(post);
      expect(mockPostsClient.request).toHaveBeenCalledWith(
        expect.objectContaining({
          method: 'POST',
          url: '/posts',
          data: dto,
          policy: { retry: false },
        }),
      );
    });
  });
});
